# musl does not include a g++ compiler
- name: Symlink g++ compiler for musl targets
  env:
    TARGETS: ${{ join(matrix.targets, '-') }}
  if: contains(env.TARGETS, 'x86_64-unknown-linux-musl')
  run: |
    sudo ln -s /usr/bin/g++ /usr/bin/musl-g++
    ls -l /usr/bin/musl-g++
